name: Publish to PyPI

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check if version already exists on PyPI
        id: check-version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          EXISTS=$(curl -s https://pypi.org/pypi/quantiq/json | jq -r ".releases[\"$VERSION\"] != null")
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT
        env:
          PYTHONUNBUFFERED: 1

      - name: Publish to PyPI
        if: steps.check-version.outputs.exists != 'true'
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
